### PR TITLE
Default render style in subscriber

### PR DESCRIPTION
**Pull request by tushar-1health**

### CODE REVIEW

**Comment by tushar-1health** [comment]
@sean-perkins @triniwiz Could you guys please merge this ASAP. We would like to use this in our prod app.

Thanks

**Comment by tushar-1health** [comment]
@sean-perkins @triniwiz Can you release this commit in the new version on npm so that we can use in our prod app.

**Comment by tushar-1health** [comment]
@sean-perkins @triniwiz Any update on this?

Regards

**Comment by tushar-1health** [comment]
hey @sean-perkins  @triniwiz Please release this version on npm. I am unable to release until we get this.
Sorry for bothering you alot.

Regards

**Comment by sean-perkins** [comment]
@tushar-1health The latest code has been pushed to NPM. In the future, I would strongly recommend maintaining a fork of this project. Especially if you have this used in a production environment. That way you can manage adjustments needed for your implementation, as well as pull up-stream changes as we implement our own fixes. You are able to push your own fork to npm under a different package name (adjusting the `package.json`) and you would be in business.

**Pull request merged**
